import type { Breed } from '../types';

export const breedDatabase: Breed[] = [
  {
    name: "Labrador Retriever",
    traits: ["family_friendly", "gentle", "moderate_exercise", "medium", "large", "easy_training", "moderate_grooming"],
    description: "Friendly, outgoing, and active companions who have more than enough affection to go around for a family looking for a medium to large dog.",
    size: "large",
    energy: "high",
    weight: "55-80 lbs",
    height: "21.5-24.5 inches",
    lifespan: "10-12 years",
    grooming: "Moderate",
    training: "Easy",
    good_with_kids: "Excellent",
    good_with_pets: "Excellent",
    temperament: ["Friendly", "Outgoing", "Active"],
    origin: "Newfoundland, Canada"
  },
  {
    name: "Golden Retriever",
    traits: ["family_friendly", "gentle", "moderate_exercise", "large", "easy_training", "high_grooming"],
    description: "Intelligent, friendly, and devoted dogs that are excellent with children and make wonderful family pets.",
    size: "large",
    energy: "high",
    weight: "55-75 lbs",
    height: "21.5-24 inches",
    lifespan: "10-12 years",
    grooming: "High",
    training: "Easy",
    good_with_kids: "Excellent",
    good_with_pets: "Excellent",
    temperament: ["Intelligent", "Friendly", "Devoted"],
    origin: "Scotland"
  },
  {
    name: "French Bulldog",
    traits: ["small", "low_exercise", "easy_training", "low_grooming", "apartment", "gentle"],
    description: "Adaptable, playful, and smart companions that don't need a lot of exercise or grooming.",
    size: "small",
    energy: "low",
    weight: "20-28 lbs",
    height: "11-13 inches",
    lifespan: "10-12 years",
    grooming: "Low",
    training: "Moderate",
    good_with_kids: "Good",
    good_with_pets: "Good",
    temperament: ["Adaptable", "Playful", "Smart"],
    origin: "France"
  },
  {
    name: "German Shepherd",
    traits: ["large", "high_exercise", "protective", "loyal", "challenging_training", "moderate_grooming", "working"],
    description: "Confident, courageous, and smart working dogs that are extremely versatile and loyal to their family.",
    size: "large",
    energy: "high",
    weight: "50-90 lbs",
    height: "22-26 inches",
    lifespan: "9-13 years",
    grooming: "Moderate-High",
    training: "Moderate",
    good_with_kids: "Good with proper socialization",
    good_with_pets: "Moderate",
    temperament: ["Confident", "Courageous", "Smart"],
    origin: "Germany"
  },
  {
    name: "Poodle",
    traits: ["high_grooming", "easy_training", "moderate_exercise", "medium", "intelligent"],
    description: "Intelligent, active, and elegant dogs with wonderful personalities. Available in three sizes.",
    size: "medium",
    energy: "moderate",
    weight: "4-70 lbs (varies by size)",
    height: "10-27 inches (varies by size)",
    lifespan: "12-15 years",
    grooming: "High",
    training: "Easy",
    good_with_kids: "Good",
    good_with_pets: "Good",
    temperament: ["Intelligent", "Active", "Alert"],
    origin: "Germany/France"
  },
  {
    name: "Bulldog",
    traits: ["low_exercise", "gentle", "medium", "low_grooming", "calm", "apartment"],
    description: "Calm, courageous, and friendly dogs that make excellent companions for apartment living.",
    size: "medium",
    energy: "low",
    weight: "40-50 lbs",
    height: "14-15 inches",
    lifespan: "8-10 years",
    grooming: "Low",
    training: "Moderate",
    good_with_kids: "Excellent",
    good_with_pets: "Good",
    temperament: ["Calm", "Courageous", "Friendly"],
    origin: "England"
  },
  {
    name: "Beagle",
    traits: ["family_friendly", "moderate_exercise", "medium", "moderate_grooming", "gentle"],
    description: "Loving, curious, and merry dogs that make great family pets and are excellent with children.",
    size: "medium",
    energy: "moderate",
    weight: "20-30 lbs",
    height: "13-15 inches",
    lifespan: "10-15 years",
    grooming: "Low",
    training: "Moderate",
    good_with_kids: "Excellent",
    good_with_pets: "Good",
    temperament: ["Loving", "Curious", "Merry"],
    origin: "England"
  },
  {
    name: "Rottweiler",
    traits: ["large", "protective", "loyal", "challenging_training", "moderate_exercise", "working"],
    description: "Loyal, loving, and confident guardians that are calm and courageous with proper training.",
    size: "large",
    energy: "moderate",
    weight: "80-135 lbs",
    height: "22-27 inches",
    lifespan: "8-10 years",
    grooming: "Low",
    training: "Moderate-Difficult",
    good_with_kids: "Good with proper socialization",
    good_with_pets: "Moderate",
    temperament: ["Loyal", "Loving", "Confident"],
    origin: "Germany"
  },
  {
    name: "Yorkshire Terrier",
    traits: ["small", "low_exercise", "high_grooming", "apartment", "lap_dog"],
    description: "Small but mighty terriers with big personalities, perfect for apartment living.",
    size: "small",
    energy: "moderate",
    weight: "4-7 lbs",
    height: "7-8 inches",
    lifespan: "13-16 years",
    grooming: "High",
    training: "Moderate",
    good_with_kids: "Better with older children",
    good_with_pets: "Moderate",
    temperament: ["Affectionate", "Sprightly", "Tomboyish"],
    origin: "England"
  },
  {
    name: "Siberian Husky",
    traits: ["large", "high_exercise", "energetic", "challenging_training", "moderate_grooming", "working"],
    description: "Outgoing and mischievous dogs bred for sledding who need lots of exercise and mental stimulation.",
    size: "large",
    energy: "high",
    weight: "35-60 lbs",
    height: "20-23.5 inches",
    lifespan: "12-15 years",
    grooming: "Moderate-High",
    training: "Difficult",
    good_with_kids: "Good",
    good_with_pets: "Moderate",
    temperament: ["Outgoing", "Mischievous", "Loyal"],
    origin: "Siberia"
  },
  {
    name: "Border Collie",
    traits: ["medium", "high_exercise", "energetic", "easy_training", "moderate_grooming", "working"],
    description: "Highly intelligent and energetic herding dogs that excel in agility and obedience.",
    size: "medium",
    energy: "high",
    weight: "30-55 lbs",
    height: "18-22 inches",
    lifespan: "12-15 years",
    grooming: "Moderate",
    training: "Easy",
    good_with_kids: "Good with active families",
    good_with_pets: "Good",
    temperament: ["Intelligent", "Energetic", "Responsive"],
    origin: "Scotland/England border"
  },
  {
    name: "Great Dane",
    traits: ["giant", "moderate_exercise", "gentle", "easy_training", "low_grooming", "gentle_giant"],
    description: "Gentle giants known for their friendly nature and impressive size.",
    size: "giant",
    energy: "moderate",
    weight: "110-175 lbs",
    height: "28-34 inches",
    lifespan: "8-10 years",
    grooming: "Low",
    training: "Moderate",
    good_with_kids: "Excellent",
    good_with_pets: "Good",
    temperament: ["Gentle", "Friendly", "Patient"],
    origin: "Germany"
  }
];